// Image manifest: slot id → file in /public/images. Add an entry once real photography exists;
// until then the slot renders its art-direction caption as a placeholder.
// Slot ids follow the reference: p-{productId}-1..4 (front ¾, profile, detail, in room), p-{id}-space,
// story-1..4, col-*, collection-*, home-edit-hero, statement, philosophy-detail, hero-poster.
//
// Product shots p-*-1 / p-*-2 are stand-in stock photography from Unsplash (Unsplash License: free for
// commercial use, attribution not required) until HALDEN's own product photography exists.
export const IMAGES: Record<string, string> = {
  'p-form-bench-1': '/images/p-form-bench-1.jpg',
  'p-form-bench-2': '/images/p-form-bench-2.jpg',
  'p-olympic-bar-1': '/images/p-olympic-bar-1.jpg',
  'p-olympic-bar-2': '/images/p-olympic-bar-2.jpg',
  'p-monolith-dumbbells-1': '/images/p-monolith-dumbbells-1.jpg',
  'p-monolith-dumbbells-2': '/images/p-monolith-dumbbells-2.jpg',
  'p-axis-cable-1': '/images/p-axis-cable-1.jpg',
  'p-axis-cable-2': '/images/p-axis-cable-2.jpg',
  'p-line-treadmill-1': '/images/p-line-treadmill-1.jpg',
  'p-line-treadmill-2': '/images/p-line-treadmill-2.jpg',
  'p-adjust-kettlebell-1': '/images/p-adjust-kettlebell-1.jpg',
  'p-adjust-kettlebell-2': '/images/p-adjust-kettlebell-2.jpg',
  'p-still-rower-1': '/images/p-still-rower-1.jpg',
  'p-still-rower-2': '/images/p-still-rower-2.jpg',
  'p-ledge-rack-1': '/images/p-ledge-rack-1.jpg',
  'p-ledge-rack-2': '/images/p-ledge-rack-2.jpg',
  'p-recovery-set-1': '/images/p-recovery-set-1.jpg',
  'p-recovery-set-2': '/images/p-recovery-set-2.jpg',
  'p-ground-mat-1': '/images/p-ground-mat-1.jpg',
  'p-ground-mat-2': '/images/p-ground-mat-2.jpg',
  'p-arc-mirror-1': '/images/p-arc-mirror-1.jpg',
  'p-arc-mirror-2': '/images/p-arc-mirror-2.jpg',
  'p-studio-towels-1': '/images/p-studio-towels-1.jpg',
  'p-studio-towels-2': '/images/p-studio-towels-2.jpg',
  'p-vessel-bottle-1': '/images/p-vessel-bottle-1.jpg',
  'p-vessel-bottle-2': '/images/p-vessel-bottle-2.jpg',
  'p-plinth-lamp-1': '/images/p-plinth-lamp-1.jpg',
  'p-plinth-lamp-2': '/images/p-plinth-lamp-2.jpg',
  'p-tray-organiser-1': '/images/p-tray-organiser-1.jpg',
  'p-tray-organiser-2': '/images/p-tray-organiser-2.jpg',
};

export const IMAGE_CREDITS: Record<string, { author: string; url: string }> = {
  'p-form-bench-1': { author: "LIFE FIT", url: 'https://unsplash.com/photos/a-black-bench-sitting-on-top-of-a-gray-floor-A1I0n1dIv9Q' },
  'p-form-bench-2': { author: "Brett Jordan", url: 'https://unsplash.com/photos/black-and-gray-exercise-equipment-7UZDIX4CmOU' },
  'p-olympic-bar-1': { author: "Victor Freitas", url: 'https://unsplash.com/photos/black-barbell-on-tile-flooring-Yuv-iwByVRQ' },
  'p-olympic-bar-2': { author: "Rodrigo Rodrigues | WOLF Λ R T", url: 'https://unsplash.com/photos/a-close-up-of-a-barbell-weight-on-a-gym-floor-feR_xwPVfmI' },
  'p-monolith-dumbbells-1': { author: "VD Photography", url: 'https://unsplash.com/photos/a-couple-of-black-dumbs-sitting-on-top-of-each-other-H-qxKCedhcc' },
  'p-monolith-dumbbells-2': { author: "Luis Reyes", url: 'https://unsplash.com/photos/gray-scale-photo-of-dumbbells-mTorQ9gFfOg' },
  'p-axis-cable-1': { author: "George Pagan III", url: 'https://unsplash.com/photos/gym-equipment-with-weights-and-machines-UpJkZIv4fM4' },
  'p-axis-cable-2': { author: "Stefan Vibes", url: 'https://unsplash.com/photos/weight-stack-chain-on-gym-machine-C7ko7Oi1XqA' },
  'p-line-treadmill-1': { author: "Aalo Lens", url: 'https://unsplash.com/photos/modern-gym-with-treadmills-and-large-windows-uYnHRrm63uo' },
  'p-line-treadmill-2': { author: "Intenza Fitness", url: 'https://unsplash.com/photos/a-living-room-with-a-couch-and-a-table-5cXaSUBBqkg' },
  'p-adjust-kettlebell-1': { author: "With Mahdy", url: 'https://unsplash.com/photos/a-black-and-white-photo-of-a-kettle-Xx1Mddhazmo' },
  'p-adjust-kettlebell-2': { author: "Brunxs", url: 'https://unsplash.com/photos/a-kettlebell-rests-on-a-yoga-mat-in-sunlight-xTZV2fpE6wk' },
  'p-still-rower-1': { author: "Kyle Kranz", url: 'https://unsplash.com/photos/person-sitting-on-rowing-machine-ss1YP57gLbM' },
  'p-still-rower-2': { author: "Clay Banks", url: 'https://unsplash.com/photos/brown-wooden-boat-on-body-of-water-during-daytime-O4Tu_XdMlvk' },
  'p-ledge-rack-1': { author: "Brett Jordan", url: 'https://unsplash.com/photos/black-and-silver-dumbbells-on-black-steel-rack-NAENofLAWjE' },
  'p-ledge-rack-2': { author: "Greg Rosenke", url: 'https://unsplash.com/photos/black-and-silver-dumbbells-on-white-background-0zkJ1EsH9dY' },
  'p-recovery-set-1': { author: "Tuaans", url: 'https://unsplash.com/photos/two-rolled-yoga-mats-stand-against-a-wall-YmaOkRjoBVc' },
  'p-recovery-set-2': { author: "Alexey Demidov", url: 'https://unsplash.com/photos/a-close-up-of-a-black-object-on-a-wooden-table-7tP8sNQdYpk' },
  'p-ground-mat-1': { author: "Louise Vildmark", url: 'https://unsplash.com/photos/person-sitting-on-gray-chair-bHEoayA42qg' },
  'p-ground-mat-2': { author: "Juan Miguel Agudo", url: 'https://unsplash.com/photos/red-and-white-paper-plane-dCd1l-xtaBA' },
  'p-arc-mirror-1': { author: "Peter Muniz", url: 'https://unsplash.com/photos/modern-bathroom-vanity-with-integrated-sink-and-black-faucet-bVZcSCw0Qik' },
  'p-arc-mirror-2': { author: "Peter Muniz", url: 'https://unsplash.com/photos/modern-bathroom-with-concrete-sink-and-arched-mirror-Vwx0KlHCUTU' },
  'p-studio-towels-1': { author: "Mads Leif Hansen", url: 'https://unsplash.com/photos/stack-of-clean-white-towels-on-a-surface-qPNgpYUCW0c' },
  'p-studio-towels-2': { author: "engin akyurt", url: 'https://unsplash.com/photos/a-bunch-of-white-towels-stacked-on-top-of-each-other-mgvb4Pga_nM' },
  'p-vessel-bottle-1': { author: "Joan Tran", url: 'https://unsplash.com/photos/green-bottle-on-white-table-reEySFadyJQ' },
  'p-vessel-bottle-2': { author: "Bluewater Sweden", url: 'https://unsplash.com/photos/black-bottle-beside-clear-drinking-glass-on-brown-wooden-table-_TtCW8cfp4k' },
  'p-plinth-lamp-1': { author: "mk. s", url: 'https://unsplash.com/photos/a-lamp-sitting-next-to-a-couch-in-a-room-3LdrBCdUqVA' },
  'p-plinth-lamp-2': { author: "John Black", url: 'https://unsplash.com/photos/white-and-silver-floor-lamp-RV9T8txb2uY' },
  'p-tray-organiser-1': { author: "Sayan Majhi", url: 'https://unsplash.com/photos/smartphone-keys-multi-tool-and-earbuds-on-a-wooden-tray-yWvmFMXiBJw' },
  'p-tray-organiser-2': { author: "Oakywood", url: 'https://unsplash.com/photos/a-desk-with-a-laptop-pen-and-scissors-on-it-R60vO3uz1gc' },
};
