// Image manifest: slot id → file in /public/images. A slot without an entry renders its art-direction caption
// as a placeholder. Slot ids follow the reference: p-{productId}-1..4 (front ¾, profile/alternate, detail, in room),
// p-{id}-space, story-1..4, col-*, collection-*, home-edit-hero, statement, philosophy-detail, hero-poster.
//
// Every image below is stand-in stock photography from Unsplash (Unsplash License: free for commercial use,
// attribution not required), chosen to match each slot's caption, until HALDEN's own photography exists.
export const IMAGES: Record<string, string> = {
  'p-form-bench-1': '/images/p-form-bench-1.jpg',
  'p-form-bench-2': '/images/p-form-bench-2.jpg',
  'p-olympic-bar-1': '/images/p-olympic-bar-1.jpg',
  'p-olympic-bar-2': '/images/p-olympic-bar-2.jpg',
  'p-monolith-dumbbells-1': '/images/p-monolith-dumbbells-1.jpg',
  'p-monolith-dumbbells-2': '/images/p-monolith-dumbbells-2.jpg',
  'p-axis-cable-1': '/images/p-axis-cable-1.jpg',
  'p-axis-cable-2': '/images/p-axis-cable-2.jpg',
  'p-line-treadmill-1': '/images/p-line-treadmill-1.jpg',
  'p-line-treadmill-2': '/images/p-line-treadmill-2.jpg',
  'p-adjust-kettlebell-1': '/images/p-adjust-kettlebell-1.jpg',
  'p-adjust-kettlebell-2': '/images/p-adjust-kettlebell-2.jpg',
  'p-still-rower-1': '/images/p-still-rower-1.jpg',
  'p-still-rower-2': '/images/p-still-rower-2.jpg',
  'p-ledge-rack-1': '/images/p-ledge-rack-1.jpg',
  'p-ledge-rack-2': '/images/p-ledge-rack-2.jpg',
  'p-recovery-set-1': '/images/p-recovery-set-1.jpg',
  'p-recovery-set-2': '/images/p-recovery-set-2.jpg',
  'p-ground-mat-1': '/images/p-ground-mat-1.jpg',
  'p-ground-mat-2': '/images/p-ground-mat-2.jpg',
  'p-arc-mirror-1': '/images/p-arc-mirror-1.jpg',
  'p-arc-mirror-2': '/images/p-arc-mirror-2.jpg',
  'p-studio-towels-1': '/images/p-studio-towels-1.jpg',
  'p-studio-towels-2': '/images/p-studio-towels-2.jpg',
  'p-vessel-bottle-1': '/images/p-vessel-bottle-1.jpg',
  'p-vessel-bottle-2': '/images/p-vessel-bottle-2.jpg',
  'p-plinth-lamp-1': '/images/p-plinth-lamp-1.jpg',
  'p-plinth-lamp-2': '/images/p-plinth-lamp-2.jpg',
  'p-tray-organiser-1': '/images/p-tray-organiser-1.jpg',
  'p-tray-organiser-2': '/images/p-tray-organiser-2.jpg',
  'p-form-bench-3': '/images/p-form-bench-3.jpg',
  'p-form-bench-4': '/images/p-form-bench-4.jpg',
  'p-olympic-bar-3': '/images/p-olympic-bar-3.jpg',
  'p-olympic-bar-4': '/images/p-olympic-bar-4.jpg',
  'p-monolith-dumbbells-3': '/images/p-monolith-dumbbells-3.jpg',
  'p-monolith-dumbbells-4': '/images/p-monolith-dumbbells-4.jpg',
  'p-axis-cable-3': '/images/p-axis-cable-3.jpg',
  'p-axis-cable-4': '/images/p-axis-cable-4.jpg',
  'p-line-treadmill-3': '/images/p-line-treadmill-3.jpg',
  'p-line-treadmill-4': '/images/p-line-treadmill-4.jpg',
  'p-adjust-kettlebell-3': '/images/p-adjust-kettlebell-3.jpg',
  'p-adjust-kettlebell-4': '/images/p-adjust-kettlebell-4.jpg',
  'p-still-rower-3': '/images/p-still-rower-3.jpg',
  'p-still-rower-4': '/images/p-still-rower-4.jpg',
  'p-ledge-rack-3': '/images/p-ledge-rack-3.jpg',
  'p-ledge-rack-4': '/images/p-ledge-rack-4.jpg',
  'p-recovery-set-3': '/images/p-recovery-set-3.jpg',
  'p-recovery-set-4': '/images/p-recovery-set-4.jpg',
  'p-ground-mat-3': '/images/p-ground-mat-3.jpg',
  'p-ground-mat-4': '/images/p-ground-mat-4.jpg',
  'p-arc-mirror-3': '/images/p-arc-mirror-3.jpg',
  'p-arc-mirror-4': '/images/p-arc-mirror-4.jpg',
  'p-studio-towels-3': '/images/p-studio-towels-3.jpg',
  'p-studio-towels-4': '/images/p-studio-towels-4.jpg',
  'p-vessel-bottle-3': '/images/p-vessel-bottle-3.jpg',
  'p-vessel-bottle-4': '/images/p-vessel-bottle-4.jpg',
  'p-plinth-lamp-3': '/images/p-plinth-lamp-3.jpg',
  'p-plinth-lamp-4': '/images/p-plinth-lamp-4.jpg',
  'p-tray-organiser-3': '/images/p-tray-organiser-3.jpg',
  'p-tray-organiser-4': '/images/p-tray-organiser-4.jpg',
  'p-form-bench-space': '/images/p-form-bench-space.jpg',
  'p-olympic-bar-space': '/images/p-olympic-bar-space.jpg',
  'p-monolith-dumbbells-space': '/images/p-monolith-dumbbells-space.jpg',
  'p-axis-cable-space': '/images/p-axis-cable-space.jpg',
  'p-line-treadmill-space': '/images/p-line-treadmill-space.jpg',
  'p-adjust-kettlebell-space': '/images/p-adjust-kettlebell-space.jpg',
  'p-still-rower-space': '/images/p-still-rower-space.jpg',
  'p-ledge-rack-space': '/images/p-ledge-rack-space.jpg',
  'p-recovery-set-space': '/images/p-recovery-set-space.jpg',
  'p-ground-mat-space': '/images/p-ground-mat-space.jpg',
  'p-arc-mirror-space': '/images/p-arc-mirror-space.jpg',
  'p-studio-towels-space': '/images/p-studio-towels-space.jpg',
  'p-vessel-bottle-space': '/images/p-vessel-bottle-space.jpg',
  'p-plinth-lamp-space': '/images/p-plinth-lamp-space.jpg',
  'p-tray-organiser-space': '/images/p-tray-organiser-space.jpg',
  'col-strength': '/images/col-strength.jpg',
  'col-cardio': '/images/col-cardio.jpg',
  'col-homegym': '/images/col-homegym.jpg',
  'col-accessories': '/images/col-accessories.jpg',
  'story-1': '/images/story-1.jpg',
  'story-2': '/images/story-2.jpg',
  'story-3': '/images/story-3.jpg',
  'story-4': '/images/story-4.jpg',
  'home-edit-hero': '/images/home-edit-hero.jpg',
  'statement': '/images/statement.jpg',
  'philosophy-detail': '/images/philosophy-detail.jpg',
  'collection-strength': '/images/collection-strength.jpg',
  'collection-cardio': '/images/collection-cardio.jpg',
  'collection-home-gym': '/images/collection-home-gym.jpg',
  'collection-accessories': '/images/collection-accessories.jpg',
  'collection-home': '/images/collection-home.jpg',
};

export const IMAGE_CREDITS: Record<string, { author: string; url: string }> = {
  'p-form-bench-1': { author: "LIFE FIT", url: 'https://unsplash.com/photos/a-black-bench-sitting-on-top-of-a-gray-floor-A1I0n1dIv9Q' },
  'p-form-bench-2': { author: "Brett Jordan", url: 'https://unsplash.com/photos/black-and-gray-exercise-equipment-7UZDIX4CmOU' },
  'p-olympic-bar-1': { author: "Victor Freitas", url: 'https://unsplash.com/photos/black-barbell-on-tile-flooring-Yuv-iwByVRQ' },
  'p-olympic-bar-2': { author: "Rodrigo Rodrigues | WOLF Λ R T", url: 'https://unsplash.com/photos/a-close-up-of-a-barbell-weight-on-a-gym-floor-feR_xwPVfmI' },
  'p-monolith-dumbbells-1': { author: "VD Photography", url: 'https://unsplash.com/photos/a-couple-of-black-dumbs-sitting-on-top-of-each-other-H-qxKCedhcc' },
  'p-monolith-dumbbells-2': { author: "Luis Reyes", url: 'https://unsplash.com/photos/gray-scale-photo-of-dumbbells-mTorQ9gFfOg' },
  'p-axis-cable-1': { author: "George Pagan III", url: 'https://unsplash.com/photos/gym-equipment-with-weights-and-machines-UpJkZIv4fM4' },
  'p-axis-cable-2': { author: "Stefan Vibes", url: 'https://unsplash.com/photos/weight-stack-chain-on-gym-machine-C7ko7Oi1XqA' },
  'p-line-treadmill-1': { author: "Aalo Lens", url: 'https://unsplash.com/photos/modern-gym-with-treadmills-and-large-windows-uYnHRrm63uo' },
  'p-line-treadmill-2': { author: "Intenza Fitness", url: 'https://unsplash.com/photos/a-living-room-with-a-couch-and-a-table-5cXaSUBBqkg' },
  'p-adjust-kettlebell-1': { author: "With Mahdy", url: 'https://unsplash.com/photos/a-black-and-white-photo-of-a-kettle-Xx1Mddhazmo' },
  'p-adjust-kettlebell-2': { author: "Brunxs", url: 'https://unsplash.com/photos/a-kettlebell-rests-on-a-yoga-mat-in-sunlight-xTZV2fpE6wk' },
  'p-still-rower-1': { author: "Kyle Kranz", url: 'https://unsplash.com/photos/person-sitting-on-rowing-machine-ss1YP57gLbM' },
  'p-still-rower-2': { author: "Clay Banks", url: 'https://unsplash.com/photos/brown-wooden-boat-on-body-of-water-during-daytime-O4Tu_XdMlvk' },
  'p-ledge-rack-1': { author: "Brett Jordan", url: 'https://unsplash.com/photos/black-and-silver-dumbbells-on-black-steel-rack-NAENofLAWjE' },
  'p-ledge-rack-2': { author: "Greg Rosenke", url: 'https://unsplash.com/photos/black-and-silver-dumbbells-on-white-background-0zkJ1EsH9dY' },
  'p-recovery-set-1': { author: "Tuaans", url: 'https://unsplash.com/photos/two-rolled-yoga-mats-stand-against-a-wall-YmaOkRjoBVc' },
  'p-recovery-set-2': { author: "Alexey Demidov", url: 'https://unsplash.com/photos/a-close-up-of-a-black-object-on-a-wooden-table-7tP8sNQdYpk' },
  'p-ground-mat-1': { author: "Louise Vildmark", url: 'https://unsplash.com/photos/person-sitting-on-gray-chair-bHEoayA42qg' },
  'p-ground-mat-2': { author: "Juan Miguel Agudo", url: 'https://unsplash.com/photos/red-and-white-paper-plane-dCd1l-xtaBA' },
  'p-arc-mirror-1': { author: "Peter Muniz", url: 'https://unsplash.com/photos/modern-bathroom-vanity-with-integrated-sink-and-black-faucet-bVZcSCw0Qik' },
  'p-arc-mirror-2': { author: "Peter Muniz", url: 'https://unsplash.com/photos/modern-bathroom-with-concrete-sink-and-arched-mirror-Vwx0KlHCUTU' },
  'p-studio-towels-1': { author: "Mads Leif Hansen", url: 'https://unsplash.com/photos/stack-of-clean-white-towels-on-a-surface-qPNgpYUCW0c' },
  'p-studio-towels-2': { author: "engin akyurt", url: 'https://unsplash.com/photos/a-bunch-of-white-towels-stacked-on-top-of-each-other-mgvb4Pga_nM' },
  'p-vessel-bottle-1': { author: "Joan Tran", url: 'https://unsplash.com/photos/green-bottle-on-white-table-reEySFadyJQ' },
  'p-vessel-bottle-2': { author: "Bluewater Sweden", url: 'https://unsplash.com/photos/black-bottle-beside-clear-drinking-glass-on-brown-wooden-table-_TtCW8cfp4k' },
  'p-plinth-lamp-1': { author: "mk. s", url: 'https://unsplash.com/photos/a-lamp-sitting-next-to-a-couch-in-a-room-3LdrBCdUqVA' },
  'p-plinth-lamp-2': { author: "John Black", url: 'https://unsplash.com/photos/white-and-silver-floor-lamp-RV9T8txb2uY' },
  'p-tray-organiser-1': { author: "Sayan Majhi", url: 'https://unsplash.com/photos/smartphone-keys-multi-tool-and-earbuds-on-a-wooden-tray-yWvmFMXiBJw' },
  'p-tray-organiser-2': { author: "Oakywood", url: 'https://unsplash.com/photos/a-desk-with-a-laptop-pen-and-scissors-on-it-R60vO3uz1gc' },
  'p-form-bench-3': { author: "Igor Karimov", url: 'https://unsplash.com/photos/close-up-of-textured-brown-leather-material-DmxTTqZtDds' },
  'p-form-bench-4': { author: "Point3D Commercial Imaging Ltd.", url: 'https://unsplash.com/photos/black-and-gray-treadmill-near-white-wall-10_Bx7IJqGc' },
  'p-olympic-bar-3': { author: "ObjectType RAW", url: 'https://unsplash.com/photos/textured-metal-bars-creating-a-diagonal-pattern-99nH7wuAMNA' },
  'p-olympic-bar-4': { author: "Redd Francisco", url: 'https://unsplash.com/photos/a-man-squatting-down-next-to-a-barbell-in-a-gym-8LWo8v0mKik' },
  'p-monolith-dumbbells-3': { author: "Eduardo Cano Photo Co.", url: 'https://unsplash.com/photos/black-dumbbells-on-black-metal-rack-7ltjONcH_mI' },
  'p-monolith-dumbbells-4': { author: "Point3D Commercial Imaging Ltd.", url: 'https://unsplash.com/photos/exercise-equipments-inside-a-room-TEbVwp3WC0E' },
  'p-axis-cable-3': { author: "Brett Jordan", url: 'https://unsplash.com/photos/black-and-gray-metal-locker-U00w3A4iC7c' },
  'p-axis-cable-4': { author: "Andrew Kayani", url: 'https://unsplash.com/photos/a-black-and-white-photo-of-a-gym-4G08MoVJlig' },
  'p-line-treadmill-3': { author: "Hoang Trinh", url: 'https://unsplash.com/photos/a-view-of-the-inside-of-a-train-looking-down-at-the-floor-5nfu-eQPWz0' },
  'p-line-treadmill-4': { author: "Aalo Lens", url: 'https://unsplash.com/photos/modern-gym-with-treadmills-and-large-windows-asVNiNtSSXE' },
  'p-adjust-kettlebell-3': { author: "Heidi Erickson", url: 'https://unsplash.com/photos/a-row-of-kettles-lined-up-in-a-gym-CPSjcuuV8E8' },
  'p-adjust-kettlebell-4': { author: "Richard R", url: 'https://unsplash.com/photos/a-row-of-kettles-sitting-on-top-of-a-wooden-table-K7s000U-jwE' },
  'p-still-rower-3': { author: "Patrick Fore", url: 'https://unsplash.com/photos/brown-wooden-board-with-hole-bg20VZvrfvY' },
  'p-still-rower-4': { author: "Aalo Lens", url: 'https://unsplash.com/photos/modern-gym-with-exercise-equipment-and-city-view-fuyulf8cNmg' },
  'p-ledge-rack-3': { author: "Brett Jordan", url: 'https://unsplash.com/photos/black-and-gray-dumbbells-on-rack-Y2am5BvJpV8' },
  'p-ledge-rack-4': { author: "Hera Reyes", url: 'https://unsplash.com/photos/a-row-of-exercise-equipment-in-a-gym-Z6CqKIP_J18' },
  'p-recovery-set-3': { author: "Anita Austvika", url: 'https://unsplash.com/photos/a-black-vase-sitting-on-top-of-a-white-shelf-tNxsPV6_Ec0' },
  'p-recovery-set-4': { author: "Sergio Kian", url: 'https://unsplash.com/photos/a-group-of-people-doing-exercises-in-a-gym-F2vHthxp2dE' },
  'p-ground-mat-3': { author: "Samantha Sheppard", url: 'https://unsplash.com/photos/a-yoga-mat-with-two-blocks-on-top-of-it-b8Q5fHBsyik' },
  'p-ground-mat-4': { author: "Margaret Young", url: 'https://unsplash.com/photos/rolled-yoga-mats-in-a-decorative-basket-with-plants-OuMxVZS72N0' },
  'p-arc-mirror-3': { author: "Peter Muniz", url: 'https://unsplash.com/photos/modern-bathroom-with-wood-patterned-wallpaper-and-vanity-9xLmmGtEJqM' },
  'p-arc-mirror-4': { author: "Monaz Nazary", url: 'https://unsplash.com/photos/dining-set-with-chairs-and-plants-in-a-bright-room-GfwmqTIVx3U' },
  'p-studio-towels-3': { author: "MADEINEGYPT.CA", url: 'https://unsplash.com/photos/a-gray-towel-folded-on-top-of-a-bed-46g2RzaaxJ0' },
  'p-studio-towels-4': { author: "Ali Mucci", url: 'https://unsplash.com/photos/white-textile-on-brown-wooden-chair-3Sz45ULJmUE' },
  'p-vessel-bottle-3': { author: "personalgraphic.com", url: 'https://unsplash.com/photos/a-white-bottle-with-a-black-cap-OUjR8lrGccs' },
  'p-vessel-bottle-4': { author: "quokkabottles", url: 'https://unsplash.com/photos/purple-and-white-bottle-on-white-table-BojfdjV4oI8' },
  'p-plinth-lamp-3': { author: "Adrian Swancar", url: 'https://unsplash.com/photos/white-table-lamp-turned-on-near-white-wall-G12opPvmqP0' },
  'p-plinth-lamp-4': { author: "Zhang liven", url: 'https://unsplash.com/photos/a-living-room-with-a-chair-and-a-floor-lamp-bnOk0PHDm0s' },
  'p-tray-organiser-3': { author: "Joshua Bartell", url: 'https://unsplash.com/photos/brown-wooden-board-6vvIBTvL90A' },
  'p-tray-organiser-4': { author: "Isaac", url: 'https://unsplash.com/photos/ceramic-mug-on-wooden-tray-hojt4QOwGl8' },
  'p-form-bench-space': { author: "Salman Sidheek", url: 'https://unsplash.com/photos/dark-gym-interior-with-exercise-machines-and-led-lighting-ER28K86K4Ho' },
  'p-olympic-bar-space': { author: "Risen Wang", url: 'https://unsplash.com/photos/gym-equipment-inside-room-20jX9b35r_M' },
  'p-monolith-dumbbells-space': { author: "Alex Tyson", url: 'https://unsplash.com/photos/a-room-with-a-lot-of-exercise-equipment-in-it-04B4HFnxPOM' },
  'p-axis-cable-space': { author: "Salman Sidheek", url: 'https://unsplash.com/photos/dark-gym-interior-with-exercise-equipment-and-weight-machines-iW79tgCbiMs' },
  'p-line-treadmill-space': { author: "Syed Mohammad Ismail Quli", url: 'https://unsplash.com/photos/a-gym-filled-with-lots-of-exercise-equipment-_Le3AQsFwVg' },
  'p-adjust-kettlebell-space': { author: "sati", url: 'https://unsplash.com/photos/a-gym-with-a-mirror-and-a-treadmill-yqc77vmpNaM' },
  'p-still-rower-space': { author: "eran design", url: 'https://unsplash.com/photos/modern-gym-with-treadmills-and-exercise-bikes-svnEBTitOIM' },
  'p-ledge-rack-space': { author: "Andrew Kayani", url: 'https://unsplash.com/photos/a-gym-with-treadmills-and-exercise-machines-kCbCaLaiLLo' },
  'p-recovery-set-space': { author: "eran design", url: 'https://unsplash.com/photos/yoga-mats-and-props-in-a-modern-studio-PS2aiW-YOJI' },
  'p-ground-mat-space': { author: "eran design", url: 'https://unsplash.com/photos/modern-yoga-studio-with-mats-and-exercise-balls-A2gCxqX9bsI' },
  'p-arc-mirror-space': { author: "eran design", url: 'https://unsplash.com/photos/modern-gym-with-treadmills-and-stationary-bikes-X0rfCRWl690' },
  'p-studio-towels-space': { author: "eran design", url: 'https://unsplash.com/photos/modern-gym-with-treadmills-and-exercise-equipment-NTZ_696GZq8' },
  'p-vessel-bottle-space': { author: "Frederick Shaw", url: 'https://unsplash.com/photos/a-gym-with-a-lot-of-equipment-in-it-dvKnhMJWOVc' },
  'p-plinth-lamp-space': { author: "Brian Wangenheim", url: 'https://unsplash.com/photos/black-and-gray-exercise-equipment-175WMFRMoOA' },
  'p-tray-organiser-space': { author: "H&CO", url: 'https://unsplash.com/photos/a-wooden-bench-sitting-in-the-middle-of-a-room-IYfdJNXIaas' },
  'col-strength': { author: "Mirko Meister", url: 'https://unsplash.com/photos/empty-gym-with-power-rack-barbells-and-weights-j4T5z94b8ns' },
  'col-cardio': { author: "Alex Tyson", url: 'https://unsplash.com/photos/a-row-of-treadmills-in-a-gym-with-windows-CC8kc3ONwtk' },
  'col-homegym': { author: "Alex Tyson", url: 'https://unsplash.com/photos/a-gym-filled-with-lots-of-machines-and-windows-L4BybD8pvgE' },
  'col-accessories': { author: "Caroline Badran", url: 'https://unsplash.com/photos/gym-equipment-neatly-organized-on-a-wooden-wall-m56-PAdMhM0' },
  'story-1': { author: "LISK OBE", url: 'https://unsplash.com/photos/empty-wooden-bench-in-a-sunlit-room-with-large-windows-2LkJxXxGulI' },
  'story-2': { author: "Jayanth Muppaneni", url: 'https://unsplash.com/photos/a-close-up-of-a-brown-leather-texture-m5o4dOHAibM' },
  'story-3': { author: "Sven Mieke", url: 'https://unsplash.com/photos/black-cable-KdekrEcPnRU' },
  'story-4': { author: "Aalo Lens", url: 'https://unsplash.com/photos/home-gym-with-exercise-equipment-t65cRTlG9kk' },
  'home-edit-hero': { author: "Karolina Grabowska", url: 'https://unsplash.com/photos/a-lamp-and-books-on-a-table-ulh3-dLSXjI' },
  'statement': { author: "Ridhwan Nordin", url: 'https://unsplash.com/photos/woman-in-black-tank-top-and-black-pants-doing-exercise-62YFfNPCjUg' },
  'philosophy-detail': { author: "Veronika FitArt", url: 'https://unsplash.com/photos/a-wooden-table-with-a-vase-of-flowers-on-top-of-it-7cfSOLZiRpo' },
  'collection-strength': { author: "Jelmer Assink", url: 'https://unsplash.com/photos/barbell-on-rack-gzeTjGu3b_k' },
  'collection-cardio': { author: "TSENG PO-CHIA", url: 'https://unsplash.com/photos/modern-gym-with-treadmills-and-exercise-bikes-nDcP3l8dbjM' },
  'collection-home-gym': { author: "Point3D Commercial Imaging Ltd.", url: 'https://unsplash.com/photos/black-and-gray-exercise-equipment-FnMU3Hl1dMQ' },
  'collection-accessories': { author: "Margaret Young", url: 'https://unsplash.com/photos/yoga-mats-and-plants-in-a-bright-room-TKyBEqQGfCM' },
  'collection-home': { author: "Puscas Adryan", url: 'https://unsplash.com/photos/a-modern-nightstand-with-a-plant-and-lamp-5IVx5mvURJw' },
};
